### ISSUE TITLE
getting websocket Parse Error: expected HTTP/  as a response after several successful requests

### ISSUE THREAD

**Issue by jh0l** [liamcottle/rustplus.js#14]
I get this error in NodeJS console when sending requests through the RustPlus.sendRequest method
```
Error: Parse Error: Expected HTTP/
    at Socket.socketOnData (_http_client.js:509:22)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  bytesParsed: 0,
  code: 'HPE_INVALID_CONSTANT',
  reason: 'Expected HTTP/',
  rawPacket: <Buffer 88 02 03 e8>
}
Error: Parse Error: Expected HTTP/
    at Socket.socketOnData (_http_client.js:509:22)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  bytesParsed: 0,
  code: 'HPE_INVALID_CONSTANT',
  reason: 'Expected HTTP/',
  rawPacket: <Buffer 88 02 03 e8>
}
```

But this does not happen on the first request, only after several requests have been successful already.
Is this some sort of throttling message from the rust game server that cannot be read as a HTTP response?

**Comment by liamcottle** [comment]
I'm not too sure on this one sorry. Let me know if you're able to find a fix.
