### ISSUE TITLE
rustplus.js throw error "ETIMEDOUT" when rust server doesn't work because unhandled 'error' event in rustplus.js

### ISSUE THREAD

**Issue by 4vent** [liamcottle/rustplus.js#29]
rustplus.js throw error "ETIMEDOUT" because unhandled 'error' event in rustplus.js when rust server doesn't work .
So program that use rustplus.js will force stop when ETIMEDOUT occur.

**Comment by 4vent** [comment]
```js
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 58.227.90.26:28083
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
Emitted 'error' event on RustPlus instance at:
    at WebSocket.<anonymous> (C:\Users\kent\AppData\Roaming\npm\node_modules\@liamcottle\rustplus.js\rustplus.js:71:22)
    at WebSocket.emit (events.js:315:20)
    at ClientRequest.<anonymous> (C:\Users\kent\AppData\Roaming\npm\node_modules\@liamcottle\rustplus.js\node_modules\ws\lib\websocket.js:579:15)
    at ClientRequest.emit (events.js:315:20)
    at Socket.socketErrorListener (_http_client.js:469:9)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4039,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '58.227.90.26',
  port: 28083
}
```

**Comment by 4vent** [comment]
```js
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 58.227.90.26:28083
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
Emitted 'error' event on RustPlus instance at:
    at WebSocket.<anonymous> (C:\Users\***\AppData\Roaming\npm\node_modules\@liamcottle\rustplus.js\rustplus.js:71:22)
    at WebSocket.emit (events.js:315:20)
    at ClientRequest.<anonymous> (C:\Users\***\AppData\Roaming\npm\node_modules\@liamcottle\rustplus.js\node_modules\ws\lib\websocket.js:579:15)
    at ClientRequest.emit (events.js:315:20)
    at Socket.socketErrorListener (_http_client.js:469:9)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4039,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '58.227.90.26',
  port: 28083
}
```

**Comment by liamcottle** [comment]
Are you catching the error in `rustplus.on('error')` ?

**Comment by 4vent** [comment]
Oh, I could catch the error!
Sorry for my noob question and thank you for replying!
